- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: roboshop

- name: Removing old content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating directoy
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading and unzipping {{component}} code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes