- name: Setting up mongo repo
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Add MongoDB repository
  ansible.builtin.yum_repository:
    name: mongodb-org-7.0
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/7.0/x86_64/
    gpgcheck: 1
    enabled: 1
    gpgkey: https://www.mongodb.org/static/pgp/server-7.0.asc


- name: Install MongoDB Server
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - mongodb-org-shell
    - mongodb-mongosh

# - name: Rename db folder to schema
#   ansible.builtin.command:
#     cmd: mv /app/db /app/schema
#   args:
#     removes: /app/db
#     creates: /app/schema
#   when: component == "catalogue"
# - name: Rename master-data.js to catalogue.js
#   ansible.builtin.command:
#     cmd: mv /app/schema/master-data.js /app/schema/catalogue.js
#   args:
#     removes: /app/schema/master-data.js
#     creates: /app/schema/catalogue.js
#   when: component == "catalogue"

- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.bhargochat.space
    file: "/app/schema/{{component}}.js"
    idempotent: yes
